### ISSUE TITLE
Problems when running anything like SideJITServer --pair or --version give this error

### ISSUE THREAD

**Issue by Nobody5231** [nythepegasus/SideJITServer#211]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\maste\OneDrive\Desktop\SideJITServer-1.4.2\venv\Scripts\SideJITServer.exe\__main__.py", line 4, in <module>
    from SideJITServer.__main__ import start_server
  File "C:\Users\maste\OneDrive\Desktop\SideJITServer-1.4.2\venv\Lib\site-packages\SideJITServer\__init__.py", line 22, in <module>
    from pymobiledevice3.services.mobile_image_mounter import auto_mount_personalized
  File "C:\Users\maste\OneDrive\Desktop\SideJITServer-1.4.2\venv\Lib\site-packages\pymobiledevice3\services\mobile_image_mounter.py", line 15, in <module>
    from pymobiledevice3.restore.tss import TSSRequest
  File "C:\Users\maste\OneDrive\Desktop\SideJITServer-1.4.2\venv\Lib\site-packages\pymobiledevice3\restore\tss.py", line 10, in <module>
    from ipsw_parser.img4 import COMPONENT_FOURCC
ModuleNotFoundError: No module named 'ipsw_parser.img4'

i have tried to fix this by uninstalling pymobiledevice3 and reinstalling a newer version of it to no avail

**Comment by TechnicallyJackson** [comment]
I fixed it by upgrading pymobiledevice3 or `pip install -U pymobiledevice3`

**Comment by poibear** [comment]
If upgrading `pymobiledevice3` still doesn't work, you may need to also downgrade `ipsw-parser` to 1.3.4 via pip. See #206 for a solution.
